services:
  - type: web
    name: ganitquest-server
    runtime: node
    rootDir: apps/server
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_SSL
        value: "true"
      - key: DB_SYNCHRONIZE
        value: "true"
      - key: JWT_SECRET
        generateValue: true
